# Site settings
title: Seohee Park # site title
description: # site description
lang: en-US # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/eehoeskrap/eehoeskrap.github.io # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Seohee Park # author name
  bio: >- # tell to the world <a href="https://github.com/piharpi/jekyll-klise" target="_blank" rel="noopener">@github</a>.
    AI Research Engineer
  username: eehoeskrap # general username
  #  github: eehoeskrap # github username
  #  email: eehoeskrap@email.com # email adress
  avatar: /assets/img/SeoheePark.jpg # change with your own avatar
  social-github: eehoeskrap # add your Github handle
  social-linkedin: eehoeskrap # add your Linkedin handle
  social-email: eehoeskrap@gmail.com # add your Email address

# URL settings
url: "http://eehoeskrap.github.io" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 10

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jemoji
  
# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
